### ISSUE TITLE
issue when computing log-cost for data -> data bridge training

### ISSUE THREAD

**Issue by dfaroughy** [cesarali/conditional_rate_matching#5]
dimensions not matching when repeating tensor during computation of the outer prob in the log-cost function. It only happens when bridging two datasets. It works fine when starting from noise -> data. 

https://github.com/cesarali/conditional_rate_matching/blob/0927ec20bc054e26cd05e9d0b346a8646a04d8b7/src/conditional_rate_matching/models/temporal_networks/rates/crm_rates.py#L286

**Comment by cesarali** [comment]
Done
